### ISSUE TITLE
Posts que são links externos

### ISSUE THREAD

**Issue by lucas-per** [manualdousuario/orbita#109]
Apesar da URL vir abaixo de um post do Órbita que é um link externo, frequentemente me frustro por clicar em um post e ser levado para uma página externa, enquanto achava que abriria uma postagem no próprio Órbita. Há uma boa prática de referenciar links externos, associando-os a um ícone, representado por uma seta diagonal apontando para cima (conforme referência). Por ser uma boa prática, acredito que associar esse tipo de iconografia aos links externos do Órbita seria proveitoso para as pessoas.

![photo1701199396](https://github.com/manualdousuario/orbita/assets/85699854/6764fd7c-f455-4e00-99a4-4cf89d5dee6e)

**Comment by rghedin** [comment]
Talvez seja muito sutil, mas no Órbita, links externos exibem a raiz do domínio à frente do link, como neste caso:

<img width="556" alt="Captura de Tela 2023-11-28 às 16 45 05" src="https://github.com/manualdousuario/orbita/assets/19216581/a5907b94-4bc8-4ecd-90d6-9d3450ae496e">

Creio que a seta entre o título/link e a raiz do domínio do link deixaria as coisas meio sobrecarregadas — ainda mais quando for um link que tem link sem paywall e/ou tradução.

Acha a solução atual insuficiente, ou discreta demais, @lucas-per?

**Comment by lucas-per** [comment]
Para mim é insuficiente, pois me confundo bastante com o comportamento dessa interação com links externos no Órbita. E aí tem 2 coisas, a meu ver:

**1)** No desktop essa questão é mais bem resolvida, mas no mobile a URL fica abaixo do título:
![photo1701203909](https://github.com/manualdousuario/orbita/assets/85699854/3dc90250-d4f2-461f-b6bc-a8224b9c253b)

**2)** Tem uma heurística de design que fala sobre "as pessoas passarem mais tempo fora da sua página, do que nela". Ela é sobre o benefício de se reproduzir padrões disseminados pela web. Como designer, apesar dessa referência a links externos por ícones ser uma boa prática, também pode ser um viés meu.

Mas acho mesmo que essa URL associada ao post, por si só, não deixa claro que algo ali é sobre ser levado para fora do Órbita. Na primeira vez que me deparei com ela, achei que era sobre algum conteúdo desta outra página estar reproduzido no próprio post. Mesmo aprendendo esse comportamento, ainda me pego sendo levado de surpresa para fora do Órbita.

E acho, sim, que vai ficar mais poluído. Talvez essa melhoria necessite de mais revisão do que havia imaginado...

**Comment by rghedin** [comment]
Bons pontos, @lucas-per.

Fiz um commit com algumas mudanças comedidas. Basicamente, deixei o leiaute mobile idêntico ao de telas grandes, com a URL cinza, que indica link externo, na mesma linha do link/título. Dá para ver ao vivo [no nosso staging](https://staging-10d3-rghedin.wpcomstaging.com/orbita/tudo/). 

Achou que melhorou?

**Comment by lucas-per** [comment]
Pior que achei que não resolve, viu... No mobile, a maioria das URLs continuam não ficando na mesma linha devido ao tamanho dos links:

![photo1701288913](https://github.com/manualdousuario/orbita/assets/85699854/c960bd33-857a-483e-9111-59ae40d68c4f)

Vou prototipar umas ideias. Se chegar a algo digno de ser compartilhado coloco aqui, tudo bem?
