### ISSUE TITLE
Converter `main.min.js` em JavaScript inline

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/orbita#112]
Estou procurando formas de otimizar o leiaute/carregamento.

Notei que o [main.min.js](https://github.com/manualdousuario/orbita/blob/b49bfe2b7662dda98c288b10830a377d3638db4d/public/main.min.js) é bem pequenininho.

Será que não compensa (ou é melhor) convertê-lo em JavaScript inline?

**Comment by rghedin** [comment]
Hmmm, não sei. Não uso plugin de cache; isso é feito no nível do servidor.

O `main.min.js` não costuma mudar, não? (Ao contrário do `main.min.css`.) Se sim, talvez não fosse um prejuízo grande puxar o script para o rodapé “na mão”, em vez de deixá-lo a cargo do grunt. Faz sentido?

**Comment by gabrnunes** [comment]
Por enquanto não deve mudar não. acho que nesse caso não há problema.

mas, sinceramente acho que o ganho de performance será mínimo
