### ISSUE TITLE
Desacoplar/modularizar `orbita-header`

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/orbita#132]
Seria possível transformarmos o menu principal `orbita-header` (com o link de postar, menu drop-down e botões sociais) em um módulo, a ser chamado com um `[shortcode]`? Isto:

<img width="911" alt="image" src="https://github.com/manualdousuario/orbita/assets/19216581/8da7129b-cebf-41d0-9b07-826bfe219e5c">

Pergunto porque seria legal removê-lo de alguns locais, como no top 5 na capa do **Manual** e na [página de comentários do usuário](https://manualdousuario.net/orbita/meus-comentarios/).

**Comment by gabrnunes** [comment]
Dá sim.

Hoje já existe o shortcode `[orbita-header]`, bastaria remover a chamada para o `orbita_get_header_html()` dos vários lugares em que ele é invocado (menos no shortcode) e adicionar manualmente em cada página que quiser mostrar.

Talvez só não deveria remover do post pois não é uma página criada, é gerada via código.
