### ISSUE TITLE
Usar apenas ícones no menu principal

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/orbita#138]
Sugestão do leitor Borges (que não usa GitHub) e que talvez possa funcionar:

>O menu de organização poderia ser substituído por ícones. O Populares ser uma chama e o Últimos uma lista com seta. Reduziria em 1 toque para mudar a organização.
>
>O "Postar" poderia ser transformado em um ícone ou um botão com ícone, para dar mais destaque e incentivar publicações.
>
>No fim, ficariam em ordem, começando na esquerda, o botão de postar, os botões de organizar e, no final da linha à direita, os ícones de seguir, acompanhados de um pequeno texto ou palavra "Acompanhe o Órbita".

**Comment by rghedin** [comment]
Um mockup/proposta:

![mockup-menu-orbita-icones](https://github.com/manualdousuario/orbita/assets/19216581/105da5b8-d9a2-497f-9ed7-6f71200cd5ec)

Precisa ver se cabe no leiaute mobile. De repente, podemos usar um `grid` em telas pequenas para quebrar em duas linhas.

**Comment by claromes** [comment]
Curti. Só achei que destoou dos três últimos ícones.

O que acha de tirá-los?
![Captura de tela 2024-02-27 085734 (1)](https://github.com/manualdousuario/orbita/assets/28742647/97257fb5-3890-427c-b92d-e40bdb992a20)

"Populares" está ativado

**Comment by rghedin** [comment]
Hmmm, gosto!

**Comment by claromes** [comment]
Consigo ver isso mais pra semana que vem... Mas se quiser pegar, vamos revisando.

**Comment by claromes** [comment]
@rghedin Pode me mandar o link desses ícones? Vou começar a trabalhar nesse menu...

**Comment by rghedin** [comment]
Procurei um pacote de ícones que contivesse todos os de que precisamos. [Achei este](https://www.svgrepo.com/collection/akar-interface-icons/2). Sugestões:

* [Novo post](https://www.svgrepo.com/svg/378543/chat-add) (ou [este](https://www.svgrepo.com/svg/378598/edit));
* [Populares](https://www.svgrepo.com/svg/378611/fire);
* [Todos os posts](https://www.svgrepo.com/svg/378721/text-align-left);

Uma ideia que me ocorreu durante a pesquisa: um terceiro ícone, ao lado do de populares e todos os posts, que leve o leitor a uma conversa aleatória. ([Este ícone](https://www.svgrepo.com/svg/378516/arrow-shuffle).) Seria legal definir alguns parâmetros (por exemplo, somente conversas dos últimos 10 dias). Acha viável?

**Comment by claromes** [comment]
É viável. Mas prefiro focar esse PR na mudança do header e dps fazer um só para o random.

**Comment by claromes** [comment]
@rghedin Voltando aqui... Confesso que fiquei na dúvida de qual estava ativo:

![image](https://github.com/user-attachments/assets/87d35983-aa5f-43f2-b224-90dc00ac94e1)

**Comment by claromes** [comment]
Sugestão:

A opção selecionada fica sublinhada e com cor diferente. Além de um title no Postar (`Comece uma conversa ou compartilhe um link.`) e com mesmo estilo da listagem. (O meu PR ficou muito tempo aberto.)

Animado (ignore as mudanças do background):
![header](https://github.com/user-attachments/assets/1414a8bb-df94-4884-88e2-b1998a01e7ac)

Estático
![image](https://github.com/user-attachments/assets/ec15ba23-9708-4e97-a7b7-26c21fdec0b5)

**Comment by rghedin** [comment]
Gosto! Talvez até deixar a opção selecionada em negrito, para destacar mais?

Ah, um pedido que queria te fazer. As mudanças no `*.scss` que fiz no #151 não foram “convertidas” para o `main.css` (não rodei o grunt antes de fazer o commit). Implementei-as manualmente em produção. Pode fazer isso no próximo commit/release, @claromes?

**Comment by claromes** [comment]
@rghedin Encontrei uma solução mais legal... (negrito destoou muito)

![image](https://github.com/user-attachments/assets/3aa5f52e-e6f3-4a7a-88f8-407682de3563)

**Comment by rghedin** [comment]
Muito bom, @claromes!

**Comment by rghedin** [comment]
Ia fechar aqui, porém notei um detalhe que talvez dê para mexer: agora que temos um indicador bem óbvio da página ativa, talvez dê para tirar aquele `&middot;` entre “Populares” e “Tudo”. Acho que fica legível:

<img width="926" alt="Captura de Tela 2024-11-18 às 17 05 54" src="https://github.com/user-attachments/assets/38c97565-6e6a-47d8-9ac6-60a5f01d4d12">

**Comment by claromes** [comment]
PR enviado.
