### ISSUE TITLE
Maior distinção dos links de `[traduzir]` e `[sem paywal]`

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/orbita#144]
Com alguma frequência, participantes regulares do Órbita colocam links para traduções e quebradores de paywalls, mesmo o sistema tendo isso por padrão/automaticamente.

Desconfio de que tais links fiquem meio “ofuscados” no título, por serem muito parecidos com o próprio título. Exemplo:

<img width="920" alt="Captura de Tela 2024-04-23 às 13 59 33" src="https://github.com/manualdousuario/orbita/assets/19216581/f3360996-b4e4-4904-9fed-967a6be40714">

Não sei ainda como, mas seria legal destacá-los melhor na interface.

Outra melhoria desejável é incluir na mensagem “Deixe o link vazio para iniciar uma discussão…”, na tela de postagem, a informação de que links em inglês ou espanhol e de fontes com paywall são tratados automaticamente. Esta:

<img width="896" alt="Captura de Tela 2024-04-23 às 14 07 28" src="https://github.com/manualdousuario/orbita/assets/19216581/6d961634-11ca-4f66-a0b2-46151da28080">

**Comment by gabrnunes** [comment]
O `[sem paywall]` pra mim deveria vir depois da URL não?

**Comment by rghedin** [comment]
Hmm, pode ser uma maneira de destacá-lo. (Nunca foi assim.) Talvez até colocar uns ícones de presente (sem paywall) e tradução?

**Comment by gabrnunes** [comment]
Pode ser, pensei em estilizar como uma tag também, mas acho que pode confundir as pessoas que não é um link 🤔

e pq não padronizar e sempre abrir o link sem paywall? a tradução não sei se é tão relevante ehe

**Comment by rghedin** [comment]
Concordo, um leiaute de tag seria confuso.

Sobre o link ser sem paywall, acho que é importante manter o original em destaque para prestigiar os veículos/sites. O link `[sem paywall]`, acho eu, deve ser sempre uma alternativa para quando o original falha.

**Comment by rghedin** [comment]
Corrigido por #145
