### ISSUE TITLE
Campo de envio de imagem não some quando link é inserido via bookmarklet

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/orbita#146]
Imagino que o “sumiço” do campo seja disparado por JavaScript na página; como o bookmarklet preenche o campo do link, ficam os dois.

O comportamento esperado é que o campo de envio de imagem suma quando o do link estiver preenchido — e vice-versa.

Exemplo (acabou de acontecer comigo):

<img width="855" alt="Captura de Tela 2024-06-06 às 18 13 59" src="https://github.com/manualdousuario/orbita/assets/19216581/6da8edc8-6006-448e-a21a-570466feb840">

**Comment by altendorfme** [comment]
Eu validei no Chrome 125 e Firefox 126, está normal usando a versão main do Orbita

https://github.com/manualdousuario/orbita/assets/1530032/626fdbc1-e076-415e-a12e-a6fdb9e1df57

**Comment by rghedin** [comment]
O erro acontece apenas quando a inserção do link é feita pelo bookmarklet, @altendorfme. Este:

```js
javascript:window.location=%22https://manualdousuario.net/orbita/postar?u=%22+encodeURIComponent(document.location)+%22&t=%22+encodeURIComponent(document.title)
```

Talvez seja o caso de aposentar o bookmarklet? Se for muito difícil depurar e/ou resolver esse problema. Não creio que muita gente o use.

Vídeo demonstrando:

https://github.com/manualdousuario/orbita/assets/19216581/9e33ee2b-eacc-41f5-9519-e0c7d2132c1e

**Comment by altendorfme** [comment]
Ahhhhhhhhh captei vosso bug!
Tá lá! https://github.com/manualdousuario/orbita/tree/ajuste-para-bookmarklet ou [orbita.zip](https://github.com/user-attachments/files/15840388/orbita.zip)

**Comment by rghedin** [comment]
Funcionou, @altendorfme!
