### ISSUE TITLE
Erro no `main.mini.js`: TypeError: null is not an object (evaluating 't.files')

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/orbita#149]
Oi!

Estava verificando outra coisa no inspetor de elementos no **Manual** quando notei um erro no console. Expandi o erro e parece ser algo relacionado à checagem no tamanho de anexos (imagens) da implementação do upload (#120 e #123), feita pelo @altendorfme.

Alguma ideia da gravidade e de como corrigir?

<img width="350" alt="Print parcial do erro TypeError: null is not an object (evaluating ‘t.files’), no console do Safari." src="https://github.com/user-attachments/assets/b48587ea-4d08-411b-9d7a-96f34790a125">

**Comment by altendorfme** [comment]
@rghedin não é grave, é só que ta falando uma validação pra verificar se o campo de upload/arquivo existe
Vejo em brevo!
