### ISSUE TITLE
Actions para atualizar /public e versão

### ISSUE THREAD

**Issue by claromes** [manualdousuario/orbita#40]
Como é possível inserir input antes de iniciar um workflow seria interessante ter um para atualizar a versão do plugin no arquivo `orbita.php` sem precisar fazer commit.

É só inserir a versão, que pode ser minor ou não, e a action atualiza no arquivo deletando as linhas antigas e inserindo as novas. Com sed acho possível.

Também podemos ter um que roda sempre que tiver atualização no arquivo `main.scss` rodando `grunt sass` para atualizar o diretório `public`. Esse rodaria a cada novo merge, fazendo a verificação.

O que acham? Vale?

**Comment by rghedin** [comment]
Se não for muito complicado ou trabalhoso, agiliza, né?

(Culpado aqui, não sei mexer muito bem com git e devo fazer uns PRs meio zoados.)

**Comment by claromes** [comment]
> (Culpado aqui, não sei mexer muito bem com git e devo fazer uns PRs meio zoados.)

Não mesmo. Atualizar a versão e o /public é algo fácil de esquecer...
Vou olhar isso com calma e esperar um feedback do Gabriel tbm.

**Comment by gabrnunes** [comment]
Eu até tentei fazer isso, criei um Action que conseguia rodar o Grunt e tudo mais, problema é que eu não sei como "commitar" esse atualização na branch principal haha.

Até voltei ele ali se quiser ver como tá, só precisa fazer esse esquema de atualizar a versão e fazer o push pra main.

**Comment by rghedin** [comment]
Isso já está funcionando? Fui fazer uma modificação no `orbita.php` e a versão já estava atualizada na edição.

**Comment by gabrnunes** [comment]
Não, foi pq eu tinha feito o merge já haha

**Comment by gabrnunes** [comment]
Pois é, parece que sim! Eu só tive que tirar a segurança da branch `main` que exige um PR antes de fazer commit hahah. Mas acho que isso não é um problema.

Como que vamos fazer pra atualizar a versão dai?

**Comment by gabrnunes** [comment]
Na verdade outras pessoas ainda não conseguem commitar direto na `main`, só eu. Acho que não tem problema deixar assim.

**Comment by gabrnunes** [comment]
Tinha sido feito mas gerou algum outro problema e optamos por desabilitar.

https://github.com/manualdousuario/orbita/issues/64
