### ISSUE TITLE
Página dos posts não mostra fonte dos links

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/orbita#41]
Nas páginas dos posts do Órbita, o link (domínio na cor clarinha da capa) não aparece em lugar algum.

Seria legal manter isso ali. Um mockup:

<img width="905" alt="Captura de Tela 2023-02-21 às 08 56 04" src="https://user-images.githubusercontent.com/19216581/220338461-88ff65e9-f461-4fb8-a52f-1e2f1f956fcc.png">

**Comment by claromes** [comment]
Se for debate, mostrar 'debate' ou só mostra no post quando for link?

**Comment by rghedin** [comment]
Acho que só quando for link mesmo. Quando é debate fica evidente do que se trata dentro da página do post. (E ficou ainda mais; editei o CSS do Manual para deixar o link do título, quando é o caso de post de link, em azul e com underline.)

<img width="897" alt="Captura de Tela 2023-02-21 às 10 33 30" src="https://user-images.githubusercontent.com/19216581/220358817-2d517916-38cb-4cb7-abfd-be29520030fa.png">
