### ISSUE TITLE
Filtros por tipo de post

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/orbita#46]
É possível criar um filtro para posts sem links (“debates”)?

Acho que seria legal ter esse link no menu principal. Além de facilitar o acesso, pode ajudar a dissipar a ideia de que o Órbita só aceita posts de links.

(Se não der, penso em marcar os posts de debates com uma categoria mesmo, manualmente, e aí usá-la de filtro. A gente pode pensar em usos para categorias; até agora, não estão sendo usadas para nada.)

**Comment by gabrnunes** [comment]
Pra filtrar somente usando as categorias ou tags mesmo. Dá pra fazer automático... quando o usuário envia um post sem um link, coloca a tag.

**Comment by rghedin** [comment]
Necessariamente tag? Pode ser uma categoria nesse esquema automático?

**Comment by rghedin** [comment]
Criei a categoria e atribuí a ela os posts sem links publicados até agora.

Só que o link que o WordPress gera da categoria dá erro: https://manualdousuario.net/categoria/conversas/

Achei estranho. Nos posts convencionais, o slug usa `category` — exemplo funcional: http://manualdousuario.net/category/bastidores/

Alguma ideia do que está errado?

**Comment by gabrnunes** [comment]
Não sei :-(

Eu não vou conseguir ver isso agora pq tô meio corrido. Se a @claromes conseguir resolver eu consigo revisar, se não eu faço outra hora, pode ser?

**Comment by claromes** [comment]
Vou olhar...
