### ISSUE TITLE
Artefato nos botões de votação ao carregar a página

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/orbita#94]
Ao carregar uma página que lista posts do Órbita, os botões de votação (seta para cima) ficam esquisitos por uma fração, com um fundo quadrado maior e azul, de segundos antes de aparecerem com o leiaute normal.

Testei em vários navegadores: Safari e Firefox no macOS 14; Safari no iOS 17; e Fennec e Cromite (Chromium) no Android 13. Em todos o bug se manifesta.

Um vídeo curtinho demonstrando-o (Firefox, macOS):

https://github.com/manualdousuario/orbita/assets/19216581/baf036a2-4f04-4b4a-bdb5-cfcc9b9a7bf1

**Comment by gabrnunes** [comment]
Efeitos especiais :P
