### ISSUE TITLE
Menu dropdown do Órbita

### ISSUE THREAD

**Issue by lucas-per** [manualdousuario/orbita#98]
### Oportunidade de melhoria 1
Seria interessante se após uma interação com o "Menu" do Órbita, ficasse marcado para o usuário a opção selecionada (associada ao ícone de seleção), ao invés de sempre o texto informativo "Menu".
**Justificativa:** a pessoa poderá conferir na tela se a opção selecionada foi aplicada corretamente. Essa opção pode ser mais interessante para a pessoa do que saber que aquele componente é um menu, afinal, a pessoa acabou de interagir com o componente e sabe do que se trata.

### Oportunidade de melhoria 2
O "Guia de Uso" poderia ser removido do "Menu".
**Justificativa:** as 3 opções do menu não atuam sobre o mesmo "objeto". "Populares" e "Tudo" são filtros aplicados ao índice de links, enquanto o "Guia de Uso" são orientações gerais sobre a plataforma.

### Oportunidade de melhoria 3
O termo "Menu" poderia ser substituído por "Filtros", ou "Exibir".
**Justificativa:** por ser genérico, "Menu" traz pouco contexto para a pessoa. Já "Filtros/Exibir" indica melhor o que é possível fazer com o componente.

### Oportunidade de melhoria 4
O termo "Tudo" poderia ser substituído por "Ordem Cronológica"
**Justificativa:** "Tudo" também é muito genérico, permitindo à pessoa imaginar o que queira. Já "Ordem Cronológica" indica melhor o que acontecerá ao selecionar essa opção.

**Comment by rghedin** [comment]
Todas as sugestões foram acatadas e implementadas na [versão 1.8.8](https://github.com/manualdousuario/orbita/releases/tag/1.8.8).

Obrigado, @lucas-per!
